- name: "Update apt-get repo and cache || Pre-Kernel Deployment."
  apt: update_cache=yes force_apt_get=yes

- name: "Upgrade all apt packages || Pre-Kernel Deployment."
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: "Updating kernel || Pre-Kernel Deployment."
  apt:
    pkg:
    - raspberrypi-kernel-headers
    state: present
    update_cache: yes

- name: "Check if a reboot is needed on all servers || Pre-Kernel Deployment."
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: "Display Pre-Kernel install message || Pre-Kernel Deployment."
  debug:
    msg:
        - 'Things left to do:'
        - '- PI WILL REBOOT!!!'
        - '- Execute: ansible-playbook main.yaml -i inventory.yaml --tags dependency-install'

- name: "Reboot the box if kernel updated || Pre-Kernel Deployment."
  reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists